### PR TITLE
Database import is sucessful with external sites disabled

### PR DESCRIPTION
**Pull request by danactive**
Enabled more functionality during db import

Run `npm run dbimport`

### CODE REVIEW

**Comment by iaincollins** [comment]
I'm sorry I haven't looked at these Dan (and also @luntdotp) who just submitted a new PR last week.

I've been meaning to migrate the site to another provider - e.g. from RackSpace to either AWS or Heroku - as I'll be migrating every off the RackSpace service it's on by the end of February.

I've sent you an invite to core - feel free to merge code to master.

This code will, unfortunately not be deployed to live though as there is no continuous deployment set up for it (or I think there was, but like the crontabs it's broken).

Will raise an issue about that now and update that shortly. If any of you you'd like to chat about this over IRC or Slack then that would be awesome (cc @luntdotp @kynan).

I've been a lousy maintainer over the last year and would like to fix that, and to improve the structure of the API and data so make it easier to add and for anyone to contribute with open data sets. Would love to hear your thoughts on that.

**Comment by luntdotp** [comment]
@iaincollins @kynan @danactive Thanks for having a look! I've been pretty busy too but it'd be great to chat about it on Slack or (RE your comment on my issue #36) meet up, but I have no plans to be in London for a while (probably more like the summer now) so it might be a bit of a trek. :)

I might add a warning message in somewhere to say that the information may be slightly outdated soon, because it might be a while until we can get it fixed. I wish I had more time that I can put into this project but it looks like I've got a pretty busy 6 months up ahead.

**Comment by kynan** [comment]
Happy to chat on slack, which slack were you thinking?

**Comment by danactive** [comment]
Yeah, let's set a time, I'm in Pacific

**Pull request closed without merging**
